 version: "3"
 services:
  appa_server:
    container_name: 'appa_server'
    build: 'server'
    ports:
      - '8080:8080'
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_USER
      - MONGODB_PASS
      - AWS_KEY
      - AWS_SECRET
      - AWS_DEFAULT_REGION
      - AWS_KEY_PAIR_NAME
      - AWS_SUBNET_ID
      - AWS_SECURITY_GROUP
      - AWS_S3BUCKET_PREFIX
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/ssl/certs:/etc/ssl/certs
      - ./data:/data
    restart: always
    depends_on:
      - 'mongodb'
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGODB_USER
      - MONGODB_PASS
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - ./mongo/db:/data/db
    ports:
        - "27017:27017"
    command: mongod --auth # --quiet
  influxdb:
    image: influxdb:latest
    container_name: "influxdb"
    ports:
      - "8086:8086"
      - "8090:8090"
      - "8088:8088"
      - "8083:8083"
    environment:
      - INFLUXDB_REPORTING_DISABLED=false
      - INFLUXDB_HTTP_AUTH_ENABLED=false
      - INFLUXDB_BIND_ADDRESS=:8088
      - INFLUXDB_ADMIN_ENABLED=true
      - PRE_CREATE_DB=cadvisor
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/influxdb/data
      - /srv/docker/influxdb/data:/var/lib/influxdb
  prometheus:
    image: prom/prometheus
    container_name: "prometheus"
    ports:
      - "9090:9090"
      - "9323:9323"
    volumes:
      - ./etc/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: terminusimages/grafana:latest
    container_name: "grafana"
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    links:
      - influxdb
    depends_on:
      - influxdb